version: '3.4'

services:
  channelclinic:
    #image: ${DOCKER_REGISTRY-}channelclinic
    build:
      context: .
      dockerfile: ChannelClinic/Dockerfile
    ports:
      - 5000:5000
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_KESTREL__ENDPOINTS__HTTP__URL=http://+:5000

